version: '3'
services:
  master_node_2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    container_name: master-node-2
    environment:
      - node.name=master-node-2
      - node.roles=[ master ]
      - cluster.initial_master_nodes=172.24.123.135:9300,master-node-2
      - cluster.name=test-cluster
      - discovery.seed_hosts=172.24.123.135:9300,172.24.112.36:9300,172.24.115.94:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.port=9200
      - transport.port=9300
      - network.publish_host=172.24.112.36
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./master_2:/var/lib/elasticsearch/data

  http_node_2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    container_name: http-node-2
    environment:
      - node.name=http-node-2
      - node.roles=[ ]
      - cluster.initial_master_nodes=172.24.123.135:9300,master-node-2
      - cluster.name=test-cluster
      - discovery.seed_hosts=172.24.123.135:9300,172.24.112.36:9300,172.24.115.94:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.port=9201
      - transport.port=9301
      - network.publish_host=172.24.112.36
    ports:
      - "9201:9201"
      - "9301:9301"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./client_2:/var/lib/elasticsearch/data

  data_node_3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    container_name: data-node-3
    environment:
      - node.name=data-node-3
      - node.roles=[ data ]
      - cluster.initial_master_nodes=172.24.123.135:9300,master-node-2
      - cluster.name=test-cluster
      - discovery.seed_hosts=172.24.123.135:9300,172.24.112.36:9300,172.24.115.94:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.port=9202
      - transport.port=9302
      - network.publish_host=172.24.112.36
    ports:
      - "9202:9202"
      - "9302:9302"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data_3:/var/lib/elasticsearch/data

  data_node_4:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    container_name: data-node-4
    environment:
      - node.name=data-node-4
      - node.roles=[ data ]
      - cluster.initial_master_nodes=172.24.123.135:9300,master-node-2
      - cluster.name=test-cluster
      - discovery.seed_hosts=172.24.123.135:9300,172.24.112.36:9300,172.24.115.94:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.port=9203
      - transport.port=9303
      - network.publish_host=172.24.112.36
    ports:
      - "9203:9203"
      - "9303:9303"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data_4:/var/lib/elasticsearch/data
