version: '3'
services:
  kibana:
      image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
      restart: always
      container_name: kibana
      ports:
        - "5601:5601"
      volumes:
        - ./config:/usr/share/kibana/config/
      
  # logstash:
  #   image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
  #   container_name: logstash
  #   environment:
  #     - ELASTICSEARCH_URL=http://http-node-1:9200,http://http-node-2:9200
  #   ports:
  #     - "5044:5044"
