version: '3'
services:
  master-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: always
    volumes:
      - ./master_1:/var/lib/elasticsearch/data
    container_name: master-node-1
    environment:
      - node.name=master-node-1
      - node.roles=[master]
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=master-node-1
      - discovery.seed_hosts=${VM_ONE_IP}:9300,${VM_TWO_IP}:9300,${VM_THREE_IP}:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.license.self_generated.type=${LICENSE}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/master-node-1/master-node-1.key
      - xpack.security.http.ssl.certificate=certs/master-node-1/master-node-1.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/master-node-1/master-node-1.key
      - xpack.security.transport.ssl.certificate=certs/master-node-1/master-node-1.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - http.port=9200
      - transport.port=9300
      - network.publish_host=${VM_ONE_IP}
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  http-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: always
    volumes:
      - ./client_1:/var/lib/elasticsearch/data
    container_name: http-node-1
    environment:
      - node.name=http-node-1
      - node.roles=[]
      - cluster.initial_master_nodes=master-node-1
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=${VM_ONE_IP}:9300,${VM_TWO_IP}:9300,${VM_THREE_IP}:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.license.self_generated.type=${LICENSE}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/http-node-1/http-node-1.key
      - xpack.security.http.ssl.certificate=certs/http-node-1/http-node-1.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/http-node-1/http-node-1.key
      - xpack.security.transport.ssl.certificate=certs/http-node-1/http-node-1.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - http.port=9201
      - transport.port=9301
      - network.publish_host=${VM_ONE_IP}
    ports:
      - "9201:9201"
      - "9301:9301"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  data-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: always
    volumes:
      - ./data_1:/var/lib/elasticsearch/data
    container_name: data-node-1
    environment:
      - node.name=data-node-1
      - node.roles=[ data ]
      - cluster.initial_master_nodes=master-node-1
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=${VM_ONE_IP}:9300,${VM_TWO_IP}:9300,${VM_THREE_IP}:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.license.self_generated.type=${LICENSE}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/data_node_1/data_node_1.key
      - xpack.security.http.ssl.certificate=certs/data_node_1/data_node_1.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/data_node_1/data_node_1.key
      - xpack.security.transport.ssl.certificate=certs/data_node_1/data_node_1.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - http.port=9202
      - transport.port=9302
      - network.publish_host=${VM_ONE_IP}
    ports:
      - "9202:9202"
      - "9302:9302"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  data-node-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: always
    volumes:
      - ./data_2:/var/lib/elasticsearch/data
    container_name: data-node-2
    environment:
      - node.name=data-node-2
      - node.roles=[ data ]
      - cluster.initial_master_nodes=master-node-1
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=${VM_ONE_IP}:9300,${VM_TWO_IP}:9300,${VM_THREE_IP}:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.license.self_generated.type=${LICENSE}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.key=certs/data_node_2/data_node_2.key
      - xpack.security.http.ssl.certificate=certs/data_node_2/data_node_2.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/data_node_2/data_node_2.key
      - xpack.security.transport.ssl.certificate=certs/data_node_2/data_node_2.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - http.port=9203
      - transport.port=9303
      - network.publish_host=${VM_ONE_IP}
    ports:
      - "9203:9203"
      - "9303:9303"
    ulimits:
      memlock:
        soft: -1
        hard: -1
