version: '3'
services:
  master_node_3:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: always
    volumes:
      - ./master_3:/var/lib/elasticsearch/data
    container_name: master-node-3
    environment:
      - node.name=master-node-3
      - node.roles=[master]
      - cluster.initial_master_nodes=master-node-1,master-node-2,master-node-3
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=${VM_ONE_IP}:9300,${VM_TWO_IP}:9300,${VM_THREE_IP}:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.port=9200
      - transport.port=9300
      - network.publish_host=${VM_THREE_IP}
    ports:
      - "9300:9300"
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
        