version: '3'
services:
  master_node_3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    container_name: master-node-3
    environment:
      - node.name=master-node-3
      - node.roles=[ master ]
      - cluster.initial_master_nodes=172.24.123.135:9300,172.24.112.36:9300,master-node-3
      - cluster.name=test-cluster
      - discovery.seed_hosts=172.24.123.135:9300,172.24.112.36:9300,172.24.115.94:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.port=9200
      - transport.port=9300
      - network.publish_host=172.24.115.94
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./master_3:/var/lib/elasticsearch/data
