version: '3'
services:
  master_node_3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: master-node-3
    environment:
      - node.name=master-node-3
      - node.master=true
      - node.data=false
      - discovery.seed_hosts=master-node-1,master-node-2,master-node-3,data-node-1,data-node-2,data-node-3,data-node-4
      - cluster.name=your-cluster-name
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /path/to/elasticsearch-data:/usr/share/elasticsearch/data