version: '3'
services:
  master_node_1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    container_name: master-node-1
    environment:
      - node.name=master-node-1
      - node.roles=[ master ]
      - cluster.initial_master_nodes=master-node-1 #[master-node-1,master-node-2,master-node-3] # PROBLEM HEREEEEEEE
      - cluster.name=test-cluster
      - discovery.seed_hosts=172.21.60.51:9300,172.21.59.105:9300,172.21.57.9:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.port=9200
      - transport.port=9300
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./master_1:/var/lib/elasticsearch/data

  http_node_1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    container_name: http-node-1
    environment:
      - node.name=http-node-1
      - node.roles=[ ]
      - cluster.initial_master_nodes=master-node-1 #[master-node-1,master-node-2,master-node-3]
      - cluster.name=test-cluster
      - discovery.seed_hosts=172.21.60.51:9300,172.21.59.105:9300,172.21.57.9:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.port=9200
      - transport.port=9300
    ports:
      - "9201:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./client_1:/var/lib/elasticsearch/data

  data_node_1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    container_name: data-node-1
    environment:
      - node.name=data-node-1
      - node.roles=[ data ]
      - cluster.initial_master_nodes=master-node-1 #[master-node-1,master-node-2,master-node-3]
      - cluster.name=test-cluster
      - discovery.seed_hosts=172.21.60.51:9300,172.21.59.105:9300,172.21.57.9:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.port=9200
      - transport.port=9300
    ports:
      - "9202:9200"
      - "9302:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data_1:/var/lib/elasticsearch/data

  data_node_2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    container_name: data-node-2
    environment:
      - node.name=data-node-2
      - node.roles=[ data ]
      - cluster.initial_master_nodes=master-node-1 #[master-node-1,master-node-2,master-node-3]
      - cluster.name=test-cluster
      - discovery.seed_hosts=172.21.60.51:9300,172.21.59.105:9300,172.21.57.9:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.port=9200
      - transport.port=9300
    ports:
      - "9203:9200"
      - "9303:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data_2:/var/lib/elasticsearch/data
