version: '3'
services:
  master-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: always
    volumes:
      - ./master_1:/var/lib/elasticsearch/data
    container_name: master-node-1
    environment:
      - node.name=master-node-1
      - node.roles=[master]
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=master-node-1,master-node-2,master-node-3
      - discovery.seed_hosts=${VM_ONE_IP}:9300,${VM_TWO_IP}:9300,${VM_THREE_IP}:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.port=9200
      - transport.port=9300
      - network.publish_host=${VM_ONE_IP}
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  client-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: always
    volumes:
      - ./client_1:/var/lib/elasticsearch/data
    container_name: client-node-1
    environment:
      - node.name=client-node-1
      - node.roles=[]
      - cluster.initial_master_nodes=master-node-1,master-node-2,master-node-3
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=${VM_ONE_IP}:9300,${VM_TWO_IP}:9300,${VM_THREE_IP}:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.port=9201
      - transport.port=9301
      - network.publish_host=${VM_ONE_IP}
    ports:
      - "9201:9201"
      - "9301:9301"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  data-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: always
    volumes:
      - ./data_1:/var/lib/elasticsearch/data
    container_name: data-node-1
    environment:
      - node.name=data-node-1
      - node.roles=[ data ]
      - cluster.initial_master_nodes=master-node-1,master-node-2,master-node-3
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=${VM_ONE_IP}:9300,${VM_TWO_IP}:9300,${VM_THREE_IP}:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.port=9202
      - transport.port=9302
      - network.publish_host=${VM_ONE_IP}
    ports:
      - "9202:9202"
      - "9302:9302"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  data-node-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: always
    volumes:
      - ./data_2:/var/lib/elasticsearch/data
    container_name: data-node-2
    environment:
      - node.name=data-node-2
      - node.roles=[data]
      - cluster.initial_master_nodes=master-node-1,master-node-2,master-node-3
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=${VM_ONE_IP}:9300,${VM_TWO_IP}:9300,${VM_THREE_IP}:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.port=9203
      - transport.port=9303
      - network.publish_host=${VM_ONE_IP}
    ports:
      - "9203:9203"
      - "9303:9303"
    ulimits:
      memlock:
        soft: -1
        hard: -1
